site_name: "The AAA Blueprint: Godot Project Foundation for Scalability & Modding"
theme:
  name: material
  palette:
    scheme: slate
    primary: sky
    accent: amber
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy
plugins:
  - search
nav:
  - Overview: index.md
  - "Chapter 1": 01-chapter-1.md
  - "Chapter 2": 02-chapter-2.md
  - "Chapter 3": 03-chapter-3.md
  - "Chapter 4": 04-chapter-4.md
  - "Chapter 5": 05-chapter-5.md
  - "Chapter 6": 06-chapter-6.md
  - "Chapter 7": 07-chapter-7.md
  - "Chapter 8": 08-chapter-8.md
  - "Chapter 9": 09-chapter-9.md
  - "Chapter 10": 10-chapter-10.md
  - "Chapter 11": 11-chapter-11.md
  - "Chapter 12": 12-chapter-12.md
  - "Chapter 13": 13-chapter-13.md
  - "Chapter 14": 14-chapter-14.md
  - "Chapter 15": 15-chapter-15.md
  - "Chapter 16": 16-chapter-16.md
  - "Chapter 17": 17-chapter-17.md
  - "Chapter 18": 18-chapter-18.md
  - "Chapter 19": 19-chapter-19.md
  - "Chapter 20": 20-chapter-20.md
  - "Chapter 21": 21-chapter-21.md
  - "Chapter 22": 22-chapter-22.md
  - "Chapter 23": 23-chapter-23.md
